info:
  locInfo:
    mountedOn: null
    mountedOnObject: null
    mountedSaddle: 0
    floor: null
    map: 4e36960b-231d-482c-a3c5-a0a1e90d40da
    loc:
    - -14
    - 1
    - 1
    pos:
      x: 0
      y: 0
    path: null
    summonLocCleared: null
    summonLocId: null
    summonLoc: []
    teleportAnimId: null
    teleportStyle: ""
    updateid: 0
    rotation: 0
  appearance:
    portraitId: 9f6f0eb8-2811-4789-889f-c139b4806823
    offtokenPortraitId: null
    portraitFrameId: db9489e4-8b35-41e9-afd2-69c5eddf6510
    portraitRibbon: null
    backgroundId: 2b02a5ab-38ce-4406-b4a5-3889b80ab574
    anthem: null
    anthemVolume: 1
    tokenScaling: 1
    tokenZoom: 1
    portraitOffset:
      x: 0
      y: 0.1078545
    frameHueShift: 0
    frameSaturation: 1
    frameBrightness: 1
    popoutScale: 0.5
    characterName: null
    characterNamePrivate: false
    flip: false
    saddlePositions: []
  disguise:
    portraitId: null
    offtokenPortraitId: null
    portraitFrameId: null
    portraitRibbon: null
    backgroundId: null
    anthem: null
    anthemVolume: 1
    tokenScaling: 1
    tokenZoom: 1
    portraitOffset:
      x: 0
      y: 0
    frameHueShift: 0
    frameSaturation: 1
    frameBrightness: 1
    characterName: null
    characterNamePrivate: false
    flip: false
    saddlePositions: []
  settings:
    canRotate: false
    useLight: false
    lightColor:
      r: 1
      g: 1
      b: 1
      a: 1
    lightIntensity: 0.1
    lightRadius: 10
    lightFalloff: 0.1
    lightAngle: 360
  mountedBy: {}
  updateid: ace1ee7a-5446-45d0-9154-10faabc6135e
  properties:
    __typeName: monster
    monster_type: Trained Gummy Brick
    inflictedConditions:
      31daf7f6-f77c-4f73-8eab-43e2d0f123c0:
        riders: []
        stacks: 1
        duration: eoe
    titles: []
    max_hitpoints: 40
    animations:
      guid: 117af0ab-e842-488f-bcf1-8f0458517247-533
      anim:
      - animType: consumeResource
        resources:
          b9bc06dd-80f1-4f33-bc55-25c114e3300c: 1
    characterFeatures:
    - __typeName: CharacterFeature
      source: Trait
      modifiers:
      - __typeName: CharacterModifier
        source: Trait
        behavior: aura
        domains:
          CharacterFeature:6ea396c9-ea82-48cb-9b92-fb870bde84ee: true
        description: The brick completely occupies their space, blocking line of effect. The brick is hidden until they act.
        aura:
          __typeName: Aura
          display:
            hueshift: 0
            bgcolor: "#ffffffff"
            saturation: 1
            brightness: 1
          blocks_line_of_effect: true
          description: The brick completely occupies their space, blocking line of effect. The brick is hidden until they act.
          applyto: enemies
          guid: 7e2b936f-d5c4-4bdf-8c2f-6f70ef4f0a05
          modifiers: []
          radius: "0"
          seq: b701a426-b23e-4605-a164-128d0921a90f
          name: Translucent Brick
          sourceguid: 6ea396c9-ea82-48cb-9b92-fb870bde84ee
          objectid: c994501f-85ec-475e-b9f6-8113a814f8d1
        radius: "2"
        seq: 98c3a437-c69c-4c84-a758-2e8d8a03fb85
        name: Translucent Brick
        guid: 67f6ccef-ddc2-4b0a-b79a-bf8936b706b5
        sourceguid: 6ea396c9-ea82-48cb-9b92-fb870bde84ee
      implementation: 2
      name: Translucent Brick
      description: The brick completely occupies their space, blocking line of effect for enemies. The brick is hidden until they act.
      guid: 6ea396c9-ea82-48cb-9b92-fb870bde84ee
      domains:
        CharacterFeature:6ea396c9-ea82-48cb-9b92-fb870bde84ee: true
    - __typeName: CharacterFeature
      source: Character Feature
      modifiers:
      - __typeName: CharacterModifier
        source: Character Feature
        sourceguid: 3423ce33-0f14-43f1-883f-572ba7f2c581
        guid: cef47fd2-5159-42a9-b8ed-57752368608c
        behavior: triggerdisplay
        name: You Didn’t Pay Attention!
        description: ""
        ability:
          __typeName: TriggeredAbilityDisplay
          trigger: A creature moves or is force moved adjacent to the brick.
          distance: Ranged 1
          keywords: []
          name: You Didn’t Pay Attention!
          guid: 2264b49d-c4d2-496d-ae26-3cc4c9cf955a
          effect: The brick uses Engulf against the triggering creature and has a double edge.
        domains:
          CharacterFeature:3423ce33-0f14-43f1-883f-572ba7f2c581: true
      - __typeName: CharacterModifier
        source: Character Feature
        triggeredAbility:
          __typeName: TriggeredAbility
          hasManualVersion: true
          display:
            hueshift: 0
            bgcolor: "#ffffffff"
            saturation: 1
            brightness: 1
          repeatTargets: false
          abilityType: none
          triggerPrompt: A creature moves or is force moved adjacent to the brick.
          name: You Didn’t Pay Attention!
          numTargets: "1"
          persistence: []
          behaviors:
          - __typeName: ActivatedAbilityApplyOngoingEffectBehavior
            ongoingEffect: 410bfa3d-661c-4942-a80a-3ba23998db8a
            ongoingEffectCustom: false
            applyto: caster
            duration: 0
          - __typeName: ActivatedAbilityInvokeAbilityBehavior
            applyto: caster
            abilityType: named
            customAbility:
              __typeName: ActivatedAbility
              display:
                hueshift: 0
                bgcolor: "#ffffffff"
                saturation: 1
                brightness: 1
              numTargets: "1"
              repeatTargets: false
              behaviors: []
              modifiers: []
              abilityType: none
              targetType: self
              description: ""
              name: Invoked Ability
              iconid: ui-icons/skills/1.png
              guid: dfddd605-cee2-4702-af6b-8ebba044ff13
              range: 1
            invokeOnCaster: true
            runOnController: false
            namedAbility: Engulf
          modifiers: []
          targetType: self
          castImmediately: true
          guid: bd95c310-b465-434a-b7f9-b510af130f43
          strain: []
          description: ""
          trigger: custom
          mandatory: false
          iconid: ui-icons/skills/1.png
          actionResourceId: b9bc06dd-80f1-4f33-bc55-25c114e3300c
          range: 1
        sourceguid: 3423ce33-0f14-43f1-883f-572ba7f2c581
        behavior: trigger
        name: You Didn’t Pay Attention!
        description: ""
        guid: bb7439d9-ef89-49eb-bd07-9fc6bf92776b
        domains:
          CharacterFeature:3423ce33-0f14-43f1-883f-572ba7f2c581: true
      implementation: 3
      domains:
        CharacterFeature:3423ce33-0f14-43f1-883f-572ba7f2c581: true
      description: ""
      guid: 3423ce33-0f14-43f1-883f-572ba7f2c581
      name: You Didn’t Pay Attention!
    ongoingEffects: []
    availableTriggers: []
    ev: 12
    stability: 2
    walkingSpeed: 5
    cr: 1
    initiativeGrouping: f782ded3-921a-4a2c-85a1-3cb6f41dc637
    skillRatings: []
    groupid: bd6130fe-544f-43da-bb98-cd51d2ad5e85
    max_hitpoints_roll: "40"
    levelChoices: []
    monster_category: Monster
    movementSpeeds: []
    resources:
      b9bc06dd-80f1-4f33-bc55-25c114e3300c:
        __typeName: CharacterResource
        refreshid: 197a826b-5e97-41ba-85a7-c59fe08bafad-3
        used: 1
      d19658a2-4d7b-4504-af9e-1a5410fb17fd:
        __typeName: CharacterResource
        refreshid: 197a826b-5e97-41ba-85a7-c59fe08bafad-2
        used: 1
    savingThrowRatings: []
    minion: false
    notes:
    - title: Monster Notes
      text: ""
    role: Elite Hexer
    equipment: []
    damage_taken: 0
    creatureSize: "2"
    innateAttacks: []
    attributes:
      agl:
        id: agl
        baseValue: -1
      inu:
        id: inu
        baseValue: 0
      rea:
        id: rea
        baseValue: -3
      mgt:
        id: mgt
        baseValue: 2
      prs:
        id: prs
        baseValue: -2
      dex:
        __typeName: CharacterAttribute
        id: dex
    resistances:
    - __typeName: ResistanceEntry
      dr: 3
      damageType: acid
      apply: Damage Reduction
    opportunityAttack: 4
    traitNames: []
    import:
      data: |+
        Trained Gelatinous Cube    Level 1 Hexer
        Animal, Kobold    EV 16
        <b>Stamina</b> 20    <b>Immunity</b> Acid 3 Weapon 3
        <b>Speed</b> 5    <b>Size</b> 2 / <b>Stability</b> 2
        <b>Free Strike</b> 4
        Might +2    Agility -1    Reason -3    Intuition 0    Presence -2
        <b>Engulf</b> (Action) %E2%97%86 2d10 + 2 %E2%97%86 Signature
        <b>Keywords</b> Attack, Melee, Weapon
        <b>Distance</b> Melee 1<b>Target</b> 1 creature or object
        %E2%9C%A6    <b>%E2%89%A411</b>    3 acid damage; A1 dazed (save ends)
        %E2%98%85    <b>12%E2%80%9316</b>    5 acid damage; A2 dazed (save ends)
        %E2%9C%B8    <b>17</b>    7 acid damage; A3 restrained (save ends)
        <b>    Effect </b>A size 2 or smaller creature restrained by this attack is pulled into one of the cube's squares and moves with the cube. The creature takes 3 acid damage at the start of each of their turn while restrained. When restrained ends, the creature moves to the nearest unoccupied square adjacent to the cube.
        <b>    3 Malice</b> The cube attacks 1 additional target.

        <b>You Didn't Pay Attention!</b> (Free Triggered Action)
        <b>Keywords</b> -
        <b>Trigger </b>A creature moves or is force moved into the cube.
        <b>Distance</b> Self<b>Target</b> Self
        <b>Effect</b> The cube uses Engulf with a double edge.

        <b>Translucent Cube</b>
        The cube completely occupies their space, blocking line of effect on enemy attacks and abilities. The cube is hidden until they act.

      type: mcdm
    skillProficiencies: []
    keywords:
      Ooze: true
      Soulless: true
      Kobold: true
    innateActivatedAbilities:
    - __typeName: ActivatedAbility
      strain: []
      repeatTargets: false
      multipleModes: false
      display:
        hueshift: 0
        bgcolor: "#ffffffff"
        saturation: 1
        brightness: 1
      effectImplemented: false
      actionResourceId: d19658a2-4d7b-4504-af9e-1a5410fb17fd
      abilityType: none
      modeList: []
      keywords:
        Melee: true
        Weapon: true
        Strike: true
      name: Engulf
      targetType: target
      resourceNumber: ""
      objectTarget: true
      implementation: 3
      channelIncrement: 2
      numTargets: 1 + Charges
      persistence: []
      behaviors:
      - __typeName: ActivatedAbilityPowerRollBehavior
        tiers:
        - 7 acid damage; A<0 dazed (save ends)
        - 10 acid damage; A<1 dazed (save ends)
        - 14 acid damage; A<2 restrained (save ends)
        modesSelected:
        - 1
        roll: 2d10 + Might
      description: |-
        A size 2 or smaller creature restrained this way is pulled into
        the brick’s space, moves with the brick, and takes 4 acid damage at the start of each of their turns. An engulfed creature who is no longer restrained moves to the nearest unoccupied space adtjacent to the brick. The brick can have as many creatures or objects engulfed as will fit within their space.  **2 Malice:** This ability targets one additional target.
      channeledResource: 101bab52-7f7c-4bab-92c2-9f8e0cfb7ec8
      guid: 48f95f5b-2867-48be-9667-925d326022ad
      flavor: ""
      maxChannel: "2"
      channelDescription: "2 Malice: This ability targets one additional target."
      resourceCost: none
      modifiers: []
      iconid: ui-icons/skills/1.png
      categorization: Signature Ability
      range: 1
    - __typeName: ActivatedAbility
      display:
        hueshift: 0
        bgcolor: "#ffffffff"
        saturation: 1
        brightness: 1
      repeatTargets: false
      effectImplemented: false
      abilityType: none
      keywords: []
      name: You Didn't Pay Attention!
      objectTarget: true
      numTargets: 1
      persistence: []
      behaviors:
      - __typeName: ActivatedAbilityInvokeAbilityBehavior
        namedAbility: Engulf
        abilityType: named
        promptText: |-
          The brick uses Engulf against the triggering creature and has a
          double edge.
        customAbility:
          __typeName: ActivatedAbility
          display:
            hueshift: 0
            bgcolor: "#ffffffff"
            saturation: 1
            brightness: 1
          numTargets: "1"
          repeatTargets: false
          behaviors: []
          modifiers: []
          abilityType: none
          targetType: self
          description: ""
          name: Invoked Ability
          iconid: ui-icons/skills/1.png
          guid: ff213fc0-3d2a-4fac-99e7-dbcdb6b57295
          range: 1
      modifiers: []
      description: |-
        The brick uses Engulf against the triggering creature and has a
        double edge.
      categorization: Signature Ability
      flavor: ""
      strain: []
      targetType: self
      implementation: 3
      actionResourceId: 5e551b7d-17fb-4099-a303-bafb3c146f98
      iconid: ui-icons/skills/1.png
      guid: 859abff7-b270-4f09-a144-a6c1a1522606
      range: 1
  tokenType: null
  bestiaryId: d9a1bf69-e47e-450c-a1d8-d15bf60b0abd
  summonerid: null
  ownerId: ""
  partyid: null
  inactive: true
  size: 4
  createdTimestamp: 1730266376535
description: Trained Gummy Brick
parentFolder: a8626206-e35d-433a-b952-61ebe7374625
artist: null
ord: 0
ctime: 1741590316403
mtime: 1785860872390
hidden: false
id: d9a1bf69-e47e-450c-a1d8-d15bf60b0abd
